//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopDoctor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.Receptions = new HashSet<Reception>();
        }
    
        public int Id { get; set; }
        public string Fename { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime Birthdate { get; set; }
        public bool Gender { get; set; }
        public string SNILS { get; set; }
        public string Policy { get; set; }
    
        public virtual ICollection<Reception> Receptions { get; set; }
    }
}
