//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopDoctor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceptionMedicine
    {
        public int Id { get; set; }
        public int ReceptionId { get; set; }
        public int MedicineId { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Reception Reception { get; set; }
    }
}
