//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopDoctor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceprionProcedure
    {
        public int Id { get; set; }
        public int ReceptionId { get; set; }
        public int ProcedureId { get; set; }
    
        public virtual Procedure Procedure { get; set; }
        public virtual Reception Reception { get; set; }
    }
}
