//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopDoctor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recommendation
    {
        public Recommendation()
        {
            this.ReceptionsRecommendations = new HashSet<ReceptionRecommendation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ReceptionRecommendation> ReceptionsRecommendations { get; set; }
    }
}
